### ISSUE TITLE
Awesome Products Recognition

### ISSUE THREAD

**Issue by baihaozi12** [Wzj02200059/Products_Recognition#3]
Real nice framework for retail recognition. If the input images include more than 300 products will this solution work?

**Comment by Wzj02200059** [comment]
I will release the training & inference code of classification and retrieval task on next month。
By the way， Im interesting about Openset recognition、Unseen sample reject、Domain adaption。
Maybe u r more interesting about finegaine classification ？

**Comment by Wzj02200059** [comment]
Dear baihaozi12,
I push some updata, maybe u can try to training on your dataset.
The instruction readme is updata.

**Comment by baihaozi12** [comment]
Thanks for your frendly share, my friend. It mut be my supreme glory to have your wechat?
